### ISSUE TITLE
Make example pdf with *redaction* available in README.md?

### ISSUE THREAD

**Issue by danbauman77** [freelawproject/x-ray#40]
Would it be possible to link to a certain pdf file in the README.md? This pdf file would contain a "redaction" that the x-ray program would detect. Upon download, this hyperlinked pdf file would allow x-ray users to confirm the program was in working order on their respective machines.

**Comment by mlissner** [comment]
You can see a bunch in the `tests/assets` directory. I'd be happy to have a link there in the readme. Want to do a pull request?
